### ISSUE TITLE
Bitcoin Cash Fee Estimation API?

### ISSUE THREAD

**Issue by teran-mckinney** [sporestack/bitcash#1]
Can't find. Setting fees at 22 Satoshis for high priority and 16 for low priority.

If someone can find one or a couple, would be much appreciated. Probably will matter more 6+ months out from now.

https://github.com/sporestack/bitcash/blob/master/bitcash/network/fees.py

**Comment by tea-spoon** [comment]
Looks like you want help. Let's see if using @chaintip helps at all.

**Comment by chaintip** [comment]
`0.00331961 BCH`| `~   4.97 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4tzcsyy6qa7nhagv2rfg8kavznxvlgcdg3g8) to this issue by @tea-spoon.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/16), get a pull request merged with ```@chaintip fixes #1``` in the creation comment.

**Comment by adangert** [comment]
I use this right now for my own wallet, although I think the fees may be too high: https://blockdozer.com/insight-api/utils/estimatefee

**Comment by teran-mckinney** [comment]
Didn't know insight had a fee estimation api. Thanks for sharing.

**Comment by chaintip** [comment]
`0 BCH`| `~   0.00 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/16), get a pull request merged with ```@chaintip fixes #1``` in the creation comment.

**Comment by merc1er** [comment]
Default fee was set to 2 sat/byte

**Comment by teran-mckinney** [comment]
I think this is a nice to have some day, but in reality BCH will rarely ever get fees piling up and this might not be too important for a while.

**Comment by merc1er** [comment]
Could we close this @teran-mckinney?
BCH transactions with a fee equal to or greater than 1 satoshi per byte should always be accepted. There is no need for a fee estimation API 😄 

On an other note: maybe the default fee for bitcash should be 1 sat/byte instead of 2?

**Comment by teran-mckinney** [comment]
Sure. I'm open to 1 sat/byte.
