### ISSUE TITLE
Clarification around failed tests

### ISSUE THREAD

**Issue by AustEcon** [sporestack/bitcash#15]
Just working my way through the testing module. Wanting clarification around 8 failed tests.

1) 1 fail in test_transactions.py - 1 fail due to long_message() - because of change from 40 bytes to 220 bytes limit. **(see PR)**

2) 6 fails in network/test_services.py because CashExplorerBitcoinDotComAPI testnet functions don't actually exist.
- Is this intentional to keep these in? (i.e. maybe you want this to remain for completeness / a reminder)

3) 1 fail in test_wallet.py due to failure to send on testnet. ( def test_send )
- Not sure if this is left intentionally like this either.

**Comment by teran-mckinney** [comment]
1. Can you fix that?

2. Those weren't failing on my end but we can pull them out, unless those are generic ones and will be fixed by adding another testnet endpoint. Only have the one. Would rather add a second testnet endpoint and have those tests working, unless they are API-specific and not generic NetworkAPI.

3. That should work, but the whole thing is kinda glitchy. Needs to be made more robust.

**Comment by cyborg0922** [comment]
1. Yep included in custom pushdata PR
2. I'll see if it's possible to get these working...or if it's an API issue.
3. Okay. That's all good. Just wondered. Thanks :)

**Comment by teran-mckinney** [comment]
Sounds good, thank you! No problem.

**Comment by teran-mckinney** [comment]
Hey! I'm getting failed tests now.

`nosetests -vx`...

```
tests.test_wallet.TestPrivateKeyTestnet.test_get_unspent ... ok
tests.test_wallet.TestPrivateKeyTestnet.test_init_default ... ok
tests.test_wallet.TestPrivateKeyTestnet.test_repr ... ok
tests.test_wallet.TestPrivateKeyTestnet.test_send ... ERROR

======================================================================
ERROR: tests.test_wallet.TestPrivateKeyTestnet.test_send
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/user/repos/bitcash/tests/test_wallet.py", line 245, in test_send
    private_key.send([('n2eMqTT929pb1RDNuqEnxdaLau1rxy3efi', 10000, 'satoshi')])
  File "/home/user/repos/bitcash/bitcash/wallet.py", line 586, in send
    outputs, fee=fee, leftover=leftover, combine=combine, message=message, unspents=unspents
  File "/home/user/repos/bitcash/bitcash/wallet.py", line 547, in create_transaction
    return create_p2pkh_transaction(self, unspents, outputs, custom_pushdata=custom_pushdata)
  File "/home/user/repos/bitcash/bitcash/transaction.py", line 292, in create_p2pkh_transaction
    script = hex_to_bytes(unspent.script)
  File "/home/user/repos/bitcash/bitcash/utils.py", line 26, in hex_to_bytes
    if len(hexed) & 1:
TypeError: object of type 'NoneType' has no len()
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): tbch.blockdozer.com
urllib3.connectionpool: DEBUG: https://tbch.blockdozer.com:443 "GET /api/addr/bchtest:qzvsaasdvw6mt9j2rs3gyps673gj86flev3z0s40ln/utxo HTT
root: DEBUG: Estimated fee: 19848 satoshis for 4962 bytes
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 145 tests in 35.873s

FAILED (errors=1)
```

Can you take a look into this?

**Comment by cyborg0922** [comment]
My internet is down atm and I have some serious deadlines at work. I don't know when I will be able to. I can't think of why anything I've changed would affect testnet... I can look when I get internet back and see if I can generate the same error code though

**Comment by teran-mckinney** [comment]
Alright, thanks for letting me know. Sorry for the wait on my end.

I'll take a stab unless I see something from you on it. I just don't want to assume anything about the code and break what you've written.

**Comment by teran-mckinney** [comment]
Ok, thanks for letting me know! Appreciate your contributions thus far :).

**Comment by merc1er** [comment]
I think this can be closed too @teran-mckinney :)
