### ISSUE TITLE
How can I create an offline transaction?

### ISSUE THREAD

**Issue by ztlovemst11** [sporestack/bitcash#23]
I want to sign the transaction offline before sending a transaction ，at the same time, I can get the fee to broadcast the transaction. So that if the fee is  too high, I can cancel sending.
I don't know how to actually generate a transaction, because all the introductions are simple.

**Comment by ztlovemst11** [comment]
eg: >>> key.create_transaction([('1Archive1n2C579dMsAu3iC6tWzuQJz8dN', 190, 'jpy')])

what means the param '190' and 'jpy?'

**Comment by ztlovemst11** [comment]
when I user key.send([("n2eMqTT929pb1RDNuqEnxdaLau1rxy3efi", 10000, 'satoshi')]),
it always error!!!
Traceback (most recent call last):
  File "E:/zt_6.27/py2/testBCH5.py", line 7, in <module>
    print(private_key.send([("n2eMqTT929pb1RDNuqEnxdaLau1rxy3efi", 10000, 'satoshi')]))
  File "E:\zt_6.27\python\lib\site-packages\bitcash\wallet.py", line 584, in send
    outputs, fee=fee, leftover=leftover, combine=combine, message=message, unspents=unspents
  File "E:\zt_6.27\python\lib\site-packages\bitcash\wallet.py", line 545, in create_transaction
    return create_p2pkh_transaction(self, unspents, outputs)
  File "E:\zt_6.27\python\lib\site-packages\bitcash\transaction.py", line 227, in create_p2pkh_transaction
    script = hex_to_bytes(unspent.script)
  File "E:\zt_6.27\python\lib\site-packages\bitcash\utils.py", line 26, in hex_to_bytes
    if len(hexed) & 1:
TypeError: object of type 'NoneType' has no len()

**Comment by ztlovemst11** [comment]
Has anyone changed the code recently and hasn't updated it yet? All instances of creating a transaction have failed, and all returned are TypeError: object of type 'NoneType' has no len()

**Comment by teran-mckinney** [comment]
Are you using the latest git release? Can you try the last pip released version? 0.6.2 or something like that. I ran into some issues as well in testing, maybe the issue is wider spread.

You can see #15 talking about some of this.

> what means the param '190' and 'jpy?'

I think jpy is is Japanese Yen, and 190 of them. It doesn't work as we don't have that features in bitcash, it comes from bit.

**Comment by ztlovemst11** [comment]
I get it！thank very much

**Comment by ztlovemst11** [comment]
I am sure I am using the latest version, but I found that some places are different from those on github, especially servers.
