### ISSUE TITLE
Sorry about that I have a question about the txid after the transaction...

### ISSUE THREAD

**Issue by ztlovemst11** [sporestack/bitcash#25]
After successfully broadcasting a transaction using the NetworkAPI.broadcast_tx() method, how do I get the txid for this transaction? Because it is not in the data returned. I would like to ask if there is a solution in bitcash. If not, I guess I need to rely on some APIs to decode the generated transaction tx_hex and get txid from it.But it will deal with very slowly.

**Comment by cyborg0922** [comment]
There is a method called "get_transactions ()" in the ?? PrivateKey class.

I.e. your_key.get_transactions () should give you a list of txids... not exactly what you want but you will find it as the one at ?? Index 0 position I think.

**Comment by ztlovemst11** [comment]
Thank you for your answer, I successfully got the latest transaction txid.

**Comment by ztlovemst11** [comment]
@cyborg0922 Can you recommend some methods for generating bch keystore?

**Comment by cyborg0922** [comment]
Not sure sorry. Not off top of my head. Can't afford to delve into these matters these days...

**Comment by ztlovemst11** [comment]
OK,it is alright.Can I ask a less professional question? BTC , BCH, and LTC, their offline signature method can be in common use?

**Comment by teran-mckinney** [comment]
They are pretty common, I don't think they are vulnerable to what I know.

**Comment by zhtet036** [comment]
zhtett036@gmail.com
