### ISSUE TITLE
How do I get the actual fee before sending the transaction?

### ISSUE THREAD

**Issue by ztlovemst11** [sporestack/bitcash#26]
I find an explanation in bitcash:
bitcash.network.fees import get_fee
Fee = get_fee(speed='medium')  
>>>Fee = 4

the fee displayed on the real network,let me name it realFee
Fee != realFee(904 satoshi)
What did bitcash do to calculate the value of realFee?
I want to get the actual fee before sending the transaction.
I look forward to your reply.

**Comment by cyborg0922** [comment]
If you throw in fee = 1, 2 or 3 etc.. into a key.send () command or any of those other "create transaction" type functions, it will calculate the fee as 1, 2 or 3 sat/byte respectively... fee calculation should work pretty nice now after recently being fixed.

**Comment by ztlovemst11** [comment]
Thank you for your answer.
I am very much looking forward to a better solution.
Now how can I get the size of the rawtx of transaction?

**Comment by ztlovemst11** [comment]
I don't know if this is right? But the calculated value is the same as the real network feel.
fee_byte = get_fee()
tx_hex_len = len(tx_hex)
tx_hex_half = tx_hex_len/2
fee = fee_byte * (tx_hex_half+1)

**Comment by teran-mckinney** [comment]
Do a length on the transaction, I guess it should be hex so divide by two.

Eventually will use an api to pull recommended fee values, for now it's hard coded.

Yes, there's lots broken. Feel free to send PRs.

Why are you so concerned about fee amounts? They are super low in Bitcoin Cash.

**Comment by ztlovemst11** [comment]
I am not worried about whether it's fee is too high. The fee of bch is lower than other virtual currency I know. In fact, I just want to let the sender know the fees to be spent before the transaction, so that they don't need to worry if this trade will exceed their budget, or the balance on his account.
thank you very much.@cyborg0922  @teran-mckinney.
Your patient explanation has benefited me a lot.
