### ISSUE TITLE
Latest ABC / SV contentious hardfork

### ISSUE THREAD

**Issue by AustEcon** [sporestack/bitcash#28]
Hi Teran! What are you up to these days?

What is the best way to contact you to chat privately? I am interested in maybe porting bitcash over to the latest system but I'm not sure what side of the fence you're on with that and just wanted to discuss around it a bit.

There are heaps of javascript libraries out there but I think it's really nice to have a python one - even if it's basic. You never know - some heavier hitters might be willing to help out if it got good enough.

Regards
Cyborg

**Comment by teran-mckinney** [comment]
Hey!

Been busy, less technical work lately. email or Bitmessage. BM-2cUbcEfGKbVN16aVusiYDeBAtb1gj3q98M or sega01 shift+2, go-beyond.org.

Haven't followed the fork much. Probably leaning more towards ABC but happy to discuss either way.

Thanks for your message.

-Teran

**Comment by AustEcon** [comment]
I've just now relocated the repo to https://github.com/AustEcon/bitsv
Available on pypi:  https://pypi.org/project/bitsv/

**Comment by teran-mckinney** [comment]
Hey,

That is great to hear. I'm a bit busy now but I am interested in learning more about SV.

Let me do my research and get back to you.

Thanks,

Teran

**Comment by AustEcon** [comment]
Sure thing mate. Open invitation to discuss over Skype or whatever too.
