### ISSUE TITLE
Fiat currency API endpoint is incorrect

### ISSUE THREAD

**Issue by merc1er** [sporestack/bitcash#29]
`key.get_balance('usd')` gives an error as the API url is incorrect.

`'https://bitcashpay.com/api/rates/'` is called, but it should be `'https://bitpay.com/api/rates/'`. Also, BitPay defaults to BTC for crypto to fiat conversion, but they do give the BCH/BTC ratio in the same API call 😃.

The broken URL is located in `network/rates.py` at line 102.

Is anyone going to be able to fix that?

**Comment by BUYMERCIER** [comment]
Ah I managed to fix that.
@teran-mckinney could you please merge #30 and deploy to `pip`? 👍
