### ISSUE TITLE
cashexplorer.bitcoin.com was taken down, replace with api.bitcore.io?

### ISSUE THREAD

**Issue by teran-mckinney** [sporestack/bitcash#42]
Some progress here: https://github.com/teran-mckinney/bitcash

**Comment by merc1er** [comment]
I don't thing cashexplorer.bitcoin.com was ever a thing (it's explorer.bitcoin.com).
But now the API is located at rest.bitcoin.com.

I added bitcore support in #46. I would like implement rest.bitcoin.com support for redundancy :)

**Comment by teran-mckinney** [comment]
Looks like this API blocks Tor users so does cause issues that way.

**Comment by merc1er** [comment]
This issue should be fixed by #47 
> Looks like this API blocks Tor users so does cause issues that way.
Both rest.bitcoin.com and api.bitcore.io work for me on Tor Browser. Are you still experiencing this issue?

**Comment by teran-mckinney** [comment]
Ok, off topic:

```
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): trest.bitcoin.com:443
urllib3.connectionpool: DEBUG: https://trest.bitcoin.com:443 "GET /v2//rawtransactions/sendRawTransaction/01000000016450c5c7fb706f5c0cdf1b3fbb1d98b66f8d049770c61fd8763c8e8cda712b83010000006a4730440220528f7ac6565916f1ad2e4e8e8f453efa47afa349203b08a2de0e9af78d19229802202a4a00cdda40c4dfbe03ee9208ea0f6b2898a4271013e6a014c4902fa50461e64121033d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d9327824891804334ffffffff02d0070000000000001976a914e7c1345fc8f87c68170b3aa798a956c2fe6a9eff88ac64621b00000000001976a914990ef60d63b5b5964a1c2282061af45123e93fcb88ac00000000 HTTP/1.1" 404 36
```

Is it really a GET request for sending a TX? Not a POST? Also gives me a 404, but over Tor. Not sure over clearnet.

Looks like Tor Browser works with https://rest.bitcoin.com/v2/address/utxo/bitcoincash:qzfyvx77v2pmgc0vulwlfkl3uzjgh5gnmqk5hhyaa6 but the library does not. If you curl it, it blocks it (`torsocks curl`). So rest.bitcoin.com needs to configure Cloudflare to not filter by user agent.

**Comment by merc1er** [comment]
> Is it really a GET request for sending a TX? Not a POST? 

Yes, for a single transaction it is a GET.
You can also use POST for multiple transactions (as per the docs on rest.bitcoin.com).


Regarding Tor, I will ask the Bitcoin.com team if they can expedite this.

**Comment by teran-mckinney** [comment]
Gotcha. Thank you!

**Comment by merc1er** [comment]
@teran-mckinney could you close this? 👍

**Comment by teran-mckinney** [comment]
@merc1er thanks for finding this issue! https://github.com/Bitcoin-com/rest.bitcoin.com/issues/333

Good to know we have an answer now.
