### ISSUE TITLE
Push the latest release to PyPI

### ISSUE THREAD

**Issue by merwane** [sporestack/bitcash#43]
Please push the latest release with the new RATES API on PyPI

**Comment by teran-mckinney** [comment]
Hi!

I'm sorry for the wait. It seemed like Bitpay fixed the old endpoint.

I'll go ahead and push, regardless. Will update when I do.

Thanks,

Teran

**Comment by teran-mckinney** [comment]
Ok, should be pushed up.

Can that you were having problems with the old version and that this fixes it?

**Comment by merwane** [comment]
Problem solved on 0.5.2.9
Thanks!
