### ISSUE TITLE
Blockdozer is broken and the API gives 200s

### ISSUE THREAD

**Issue by teran-mckinney** [sporestack/bitcash#45]
This is a pretty bad situation as bitcash is being told everything is okay when it's not.

**Comment by merc1er** [comment]
#46

**Comment by teran-mckinney** [comment]
Hey @merc1er, may have something.

What do you think about this?

https://github.com/gcash/bchd/issues/322

https://github.com/gcash/bchd/blob/master/bchrpc/documentation/client_usage.md#python

https://medium.com/@bchd.cash/announcing-the-bchd-grpc-api-16b3a833292e

Live BCHD endpoint: bchd.greyh.at:8335

If this API works as intended, I can look into running a bchd myself, if needed.

Thank you!

**Comment by merc1er** [comment]
Thanks!
This looks interesting, but I cannot find the API endpoints documentation.

I am thinking about using this: https://rest.bitcoin.com/

It is very well documented and Bitcoin.com is probably one of the most reliable service providers for Bitcoin Cash.

**Comment by teran-mckinney** [comment]
Gotcha, I guess that is a good start for now then. gRPC is a little different, the library gets generated for you.

**Comment by merc1er** [comment]
rest.bitcoin.com is implemented in #47 :)

**Comment by merc1er** [comment]
@teran-mckinney can you close this?

**Comment by teran-mckinney** [comment]
Yup, thank you!
