### ISSUE TITLE
Testnet send fails

### ISSUE THREAD

**Issue by teran-mckinney** [sporestack/bitcash#5]
So running nosetests will run tests/test_wallet.py which will try to send on testnet.

It makes this transaction: `0100000001fccf6f80010410c7a11b1447801e61ce2c11dae0c60f6952ecfa9e4a4f6c2ff0010000006a47304402201030c0e1e59b799d2cd49bfec5ea86925537a1b28a7add6b29ba315dd6ec057802205068b5962ee57c77512984f67725967bb34e4adc25cab26e7e8325171d4fdc5f4121033d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d9327824891804334ffffffff0210270000000000001976a914e7c1345fc8f87c68170b3aa798a956c2fe6a9eff88acfaa9b704000000001976a914990ef60d63b5b5964a1c2282061af45123e93fcb88ac00000000`

Which looks valid when deserialized but Blockdozer says: Missing inputs. Code:-25

I tend to think it's a Blockdozer issue but will need to look into it more.

Broadcast TX on https://test-bch-insight.bitpay.com/ seems like it does absolutely nothing.

**Comment by teran-mckinney** [comment]
Hrmph.

https://bch-insight.bitpay.com/tx/send can broadast it fine but https://bccblock.info/tx/send cannot. Though it is a testnet transaction, I guess it's valid on both. Wonder if the cashaddress library is not translating correctly for testnet addresses.

**Comment by OverlordQ** [comment]
I dont think bccblock does testnet, only mainnet.

**Comment by OverlordQ** [comment]
So pushing it through a local bitcoind works fine:

```
$ bitcoin-cli -testnet sendrawtransaction "0100000001fccf6f80010410c7a11b1447801e61ce2c11dae0c60f6952ecfa9e4a4f6c2ff0010000006a47304402201030c0e1e59b799d2cd49bfec5ea86925537a1b28a7add6b29ba315dd6ec057802205068b5962ee57c77512984f67725967bb34e4adc25cab26e7e8325171d4fdc5f4121033d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d9327824891804334ffffffff0210270000000000001976a914e7c1345fc8f87c68170b3aa798a956c2fe6a9eff88acfaa9b704000000001976a914990ef60d63b5b5964a1c2282061af45123e93fcb88ac00000000"
17b50bc1bb49e71a336664c95e61ef00defba28df4b787dfe6dc660c5c9139f5
```

Looking up that txid shows it [got broadcast](https://www.blocktrail.com/tBCC/tx/17b50bc1bb49e71a336664c95e61ef00defba28df4b787dfe6dc660c5c9139f5)

**Comment by teran-mckinney** [comment]
Wow, no kidding. Seems like a bug in Insight.

Thanks for digging into that.

**Comment by teran-mckinney** [comment]
Ok, this does work:

```
curl https://test-bch-insight.bitpay.com/api/tx/send -d rawtx=0100000001fccf6f80010410c7a11b1447801e61ce2c11dae0c60f6952ecfa9e4a4f6c2ff0010000006a47304402201030c0e1e59b799d2cd49bfec5ea86925537a1b28a7add6b29ba315dd6ec057802205068b5962ee57c77512984f67725967bb34e4adc25cab26e7e8325171d4fdc5f4121033d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d9327824891804334ffffffff0210270000000000001976a914e7c1345fc8f87c68170b3aa798a956c2fe6a9eff88acfaa9b704000000001976a914990ef60d63b5b5964a1c2282061af45123e93fcb88ac00000000
```

Problem seems unique to Blockdozer:

```curl https://tbch.blockdozer.com/insight-api/tx/send -d rawtx=0100000001fccf6f80010410c7a11b1447801e61ce2c11dae0c60f6952ecfa9e4a4f6c2ff0010000006a47304402201030c0e1e59b799d2cd49bfec5ea86925537a1b28a7add6b29ba315dd6ec057802205068b5962ee57c77512984f67725967bb34e4adc25cab26e7e8325171d4fdc5f4121033d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d9327824891804334ffffffff0210270000000000001976a914e7c1345fc8f87c68170b3aa798a956c2fe6a9eff88acfaa9b704000000001976a914990ef60d63b5b5964a1c2282061af45123e93fcb88ac00000000
Missing inputs. Code:-25```

Meanwhile, check this out:

```curl -k https://tbcc.blockdozer.com/insight-api/tx/send -d rawtx=0100000001fccf6f80010410c7a11b1447801e61ce2c11dae0c60f6952ecfa9e4a4f6c2ff0010000006a47304402201030c0e1e59b799d2cd49bfec5ea86925537a1b28a7add6b29ba315dd6ec057802205068b5962ee57c77512984f67725967bb34e4adc25cab26e7e8325171d4fdc5f4121033d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d9327824891804334ffffffff0210270000000000001976a914e7c1345fc8f87c68170b3aa798a956c2fe6a9eff88acfaa9b704000000001976a914990ef60d63b5b5964a1c2282061af45123e93fcb88ac00000000
transaction already in block chain. Code:-27```

If I force tbcc it works.

**Comment by teran-mckinney** [comment]
I sent a message to Blockdozer via the form on the website.

I should still add the Bitpay Insight API as well.

**Comment by garceri** [comment]
@teran-mckinney We fixed the issue on blockdozer.com (there was a bad configuration on our load balancer), our apologies for the inconvenients.. Let me know if you need something else.!
And btw, thanks for bringing this to our attention.

**Comment by teran-mckinney** [comment]
Thank you! No problem at all.

I appreciate you fixing this. I confirmed on my end now that the bitcash tests are passing.
