### ISSUE TITLE
Travis CI fails

### ISSUE THREAD

**Issue by merc1er** [sporestack/bitcash#56]
I noticed that Travis CI often fails one of the jobs:
https://travis-ci.org/sporestack/bitcash/builds/633534082?utm_source=github_status&utm_medium=notification

Python 3.7 for example here but it sometimes is 3.6 or 5. I never get this locally.

It seems that it is always `private_key.send` failing, I am not sure why. Maybe some jobs are concurrent and that messes the UTXO set for `key.get_unspents`?

I will investigate that. If anyone has an idea please let me know 😄

**Comment by merc1er** [comment]
I get Cloudflare 520 errors:

> 520 Web Server Returned an Unknown Error
> The origin server returned an empty, unknown, or unexplained response to Cloudflare.

**Comment by teran-mckinney** [comment]
What did you get the Clouidflare errors from?

I am guessing the tests are running in parallel and the unspents change too quickly so one ends up failing. If they were in series this might be fine.

**Comment by merc1er** [comment]
I think rest.bitcoin.com is experiencing issues, I have seen people complain recently. I also experience these in the browser sometimes.

**Comment by teran-mckinney** [comment]
I see. That's likely the case then. I should see about serializing the Travis builds either way.

**Comment by merc1er** [comment]
Seems it's fixed: https://travis-ci.org/sporestack/bitcash/builds/634510119?utm_source=github_status&utm_medium=notification

**Comment by teran-mckinney** [comment]
Nice! Hope it wasn't just luck.
