### ISSUE TITLE
Schnorr Sign needed.

### ISSUE THREAD

**Issue by SKlayer** [sporestack/bitcash#61]

**Comment by teran-mckinney** [comment]
Could you elaborate?

**Comment by SKlayer** [comment]
> Could you elaborate?

Sorry， Schnorr sign of bch tx are more efficiency than legency secp256 sign. and it can reduce tx size and more performance. i belive schnorr will displace secp256 sign.

**Comment by SKlayer** [comment]
i impl one.

**Comment by teran-mckinney** [comment]
Do you want to submit a pull request?
