### ISSUE TITLE
add request money URI generator

### ISSUE THREAD

**Issue by mrx23dot** [sporestack/bitcash#67]
Please add a method to generate receive money links, eg:
key.request_money_uri(amount_bch=0.001, label="Product one", msg="thank you")

format:
bitcoincash:<address>[?amount=<amount>][&label=<label>][&message=<message>]
details: https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki

This URI could be used for 3rd party QR generator library.

**Comment by teran-mckinney** [comment]
These are so easy to generate that I've never once bothered.

I'm open to adding it, just not convinced it needs it.
