### ISSUE TITLE
Wrong address from PrivateKeyTestnet

### ISSUE THREAD

**Issue by anastasia-bilova** [sporestack/bitcash#7]
Hello! Thanks a lot for your library!

I have the following problem, when I generate the instance of the `PrivateKeyTestnet` and get the public address I got the address I cannot send money to:
```
>> key = PrivateKeyTestnet()
>> key.address
qq6pzzfpuf9uumjmeayfw9qtuy7w386kyy42pkdau8
```

Even if I compress it, I get the same error called `One or more input or output is invalid`:
```
>> key = PrivateKeyTestnet(wif='cMqw...')
>> key.address
qpgdlktn6ltjgxd4dz63rtn6gk6dk0wnusth8axycv
```

![selection_215](https://user-images.githubusercontent.com/35456560/41154612-4a435b6c-6b23-11e8-9a75-ef130658b46d.png)

When I send money (through [ccoin-cash](https://ccoin.cash/#txoutputs) web-site) from my own `test-net` address `mntaWjMep9AVmssAg7bd9hEHmNsuLtZDSS` to another also mine, [all goes fine](https://test-bch-insight.bitpay.com/api/txs/?address=mntaWjMep9AVmssAg7bd9hEHmNsuLtZDSS).

```
>>> len('qpgdlktn6ltjgxd4dz63rtn6gk6dk0wnusth8axycv') == len('mntaWjMep9AVmssAg7bd9hEHmNsuLtZDSS')
False
```

Can you help me with this question or even with all process to create signed offline raw transaction through your library? Thanks a lot!

**Comment by teran-mckinney** [comment]
Hi Anstasia!

I'm sorry for the wait. Have been out for a few days. I'll take a look into this and get back to you shortly. I do have some test cases with testnet, but my use has all been mainnet, so the odds of a bug with testnet are fairly high.

-Teran

**Comment by teran-mckinney** [comment]
Okay, turns out this isn't a bitcash bug afterall. ccoin.cash is using the old Bitcoin address format and hasn't updated to [cashaddr](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md). If you want to use bitcash with ccoin, you'll need to convert the cashaddr to the legacy address.

One site you can do this with is: https://cashaddr.bitcoincash.org

If you want to keep this within Python, you can do so with cashaddress: https://github.com/oskyk/cashaddress

cashaddress is already used inside this repository. You can send to legacy addresses, but the .address property will always return the cashaddr format.

I hope this helps! Let me know if you have any questions.

**Comment by teran-mckinney** [comment]
Oh, about raw transactions, just use `.create_transaction()` and it will give you something that you can broadcast, just the hex output.

https://github.com/sporestack/bitcash/blob/master/bitcash/wallet.py#L208

**Comment by anastasia-bilova** [comment]
Teran, thank you so much for your reply! 

You helped me a lot, with new converted BCH address everything works!

And thank you for your cool library!

**Comment by excalibur0922** [comment]
anastasia-bilova - I found a great library for converting between BCH and legacy addresses natively in python - https://github.com/oskyk/cashaddress - super handy little one to have in your tool belt :)

**Comment by teran-mckinney** [comment]
You're welcome! Glad I could help.

Though most of the credit goes to @ofek, he wrote the bit library for Bitcoin which I ported this from. He did 99% of the legwork.

**Comment by excalibur0922** [comment]
I would also like to thank you for this library. Absolutely amazing. You have made a huge difference to the BCH ecosystem with this, regardless of who did the original core work. Still takes effort to connect all the ports, add extra features, taylor it to BCH and make it work right out of the box.

**Comment by teran-mckinney** [comment]
Thank you! I really appreciate that. I needed it myself and I'm glad you've been able to find it useful as well.

Will close this out for now.
