### ISSUE TITLE
Testnet addresses not working

### ISSUE THREAD

**Issue by dkaparis** [sporestack/bitcash#70]
I try some simple testnet transactions from a funded address, however it raises `ValueError: Transactions must have at least one unspent.`

`get_balance()` method keeps returning 0.

Likely reason is the bitcoin.com testnet explorer is down (it shows no new block data and the latest transactions I can find there are from May 15th.)

Any option to use an alternative service?

**Comment by teran-mckinney** [comment]
What version are you using?

Should have been fixed in 0.5.3.5. See issue #63 

But, might need more work.

**Comment by dkaparis** [comment]
bitcash.__version__ is 0.5.3.5

Could it be the case that the bitcoin.com server is not returning error, just empty data?

**Comment by teran-mckinney** [comment]
It depends. It might be giving a false positive return of 0. But if it's returning any kind of error, we should be throwing an error rather than giving you back 0.

**Comment by dkaparis** [comment]
I don't know the bitcash internals, but some simple tests with http://trest.bitcoin.com/ show that the API is indeed reporting zero balance for these addresses. It appears the service was not upgraded past May 15th and is not aware of any new transactions.

Any easy way to switch the default service endpoint to use as a workaround?

**Comment by teran-mckinney** [comment]
That's not good. I hope they fix that.

https://github.com/sporestack/bitcash/blob/master/bitcash/network/services.py#L386-L396

You should be able to get rid of the BitcoinDotCom references there. Let me know if that fixes it for you.

**Comment by merc1er** [comment]
Trest.bitcoin.com is no longer maintained. 
I will submit a PR to remove it.

**Comment by teran-mckinney** [comment]
Thank you, @merc1er!

**Comment by merc1er** [comment]
Done! #71 

@dkaparis could you please try that these changes work for you too? Repo: merc1er/bitcash

**Comment by merc1er** [comment]
Also, I didn't remove trest.Bitcoin.com altogether as I was told it's "holding on by the skin of its teeth". They are currently waiting on the testnet indexer to catch up.

**Comment by teran-mckinney** [comment]
Looks good to me. @dkaparis if this works for you, I'll go ahead and merge it.

**Comment by dkaparis** [comment]
> Done! #71
> 
> @dkaparis could you please try that these changes work for you too? Repo: merc1er/bitcash

Just tried it, works for me.

**Comment by teran-mckinney** [comment]
Great! Do you need a new release as well? @merc1er, do you know if we had anything else ready for a new release?

**Comment by merc1er** [comment]
> @merc1er, do you know if we had anything else ready for a new release?

I would like to update the transaction fee thing (#66) but I haven’t started working on it yet.

**Comment by merc1er** [comment]
Let’s close this @teran-mckinney?

**Comment by teran-mckinney** [comment]
Ok!
